version: '3'

services:
   name-service:
     image: name:1.0
     ports:
       - 9080:9080
   
   ping-service:
     image: ping:1.0
     ports:
       - 9081:9081
     environment:
       NAME_HOSTNAME: name-service
     depends_on:
      - name-service